FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends iproute2 iptables procps iputils-ping && \
    rm -rf /var/lib/apt/lists/*

COPY router-entrypoint.sh /router-entrypoint.sh
RUN chmod +x /router-entrypoint.sh

CMD ["/router-entrypoint.sh"]
