# Dockerfile.node
FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

ARG USERNAME=demo
ARG PASSWORD=demo

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      openssh-server iproute2 iputils-ping net-tools iptables \
      ncat curl inetutils-traceroute dnsutils nmap && \
    rm -rf /var/lib/apt/lists/*

# create ssh run dir
RUN mkdir /var/run/sshd

# ensure sshd allows password auth (so the password will work)
RUN sed -i 's/^#*PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config || true
RUN sed -i 's/^#*PermitRootLogin .*/PermitRootLogin no/' /etc/ssh/sshd_config || true

# create the user using build args, set the password, and give them a home
RUN useradd -m -s /bin/bash ${USERNAME} && \
    echo "${USERNAME}:${PASSWORD}" | chpasswd && \
    mkdir -p /home/${USERNAME}/.ssh && chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}
RUN usermod -aG sudo ${USERNAME}
RUN apt update && \
        DEBIAN_FRONTEND=noninteractive apt install -y sudo

# copy entrypoint and make executable
COPY entrypoint-node.sh /entrypoint-node.sh
RUN chmod +x /entrypoint-node.sh

EXPOSE 22 80 9001 9002

CMD ["/entrypoint-node.sh"]

